name:                learning-junkie-api
version:             0.1.0.0
github:              "luminous-or-me/learning-junkie-api"
license:             BSD-3-Clause
author:              "Anvar Sheryatullayev"
maintainer:          "alvaro.sh03@gmail.com"
copyright:           "2024 Anvar Sheryatullayev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/luminous-or-me/learning-junkie-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- servant-server
- servant-auth
- servant-auth-server
- servant-auth-swagger
- servant-multipart
- postgresql-simple
- wai
- time
- resource-pool
- lens
- password
- string-conversions
- wai-logger
- warp
- postgresql-simple
- http-types
- swagger2
- servant-swagger
- servant-swagger-ui
- text
- bytestring
- utf8-string
- diagrams-lib
- diagrams-core
- diagrams-rasterific
- transformers
- wai-cors
- aws
- conduit
- conduit-extra
- http-conduit
- dotenv

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  learning-junkie-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-junkie-api

tests:
  learning-junkie-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-junkie-api
